// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjUNm22XMOfpVpUu9VeIhYdeDBpZPYNUM',
    appId: '1:216493554082:web:e1c497339d59689ec7dafb',
    messagingSenderId: '216493554082',
    projectId: 'nuduwawithflutter',
    authDomain: 'nuduwawithflutter.firebaseapp.com',
    storageBucket: 'nuduwawithflutter.appspot.com',
    measurementId: 'G-WJL0S20HJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaWrJpOk9MDVMstLfJpEIN5kPxRtg6atA',
    appId: '1:216493554082:android:ec3465f494271794c7dafb',
    messagingSenderId: '216493554082',
    projectId: 'nuduwawithflutter',
    storageBucket: 'nuduwawithflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFvabkzwToJabeG3AwRHMcoBDMT_q9CQ8',
    appId: '1:216493554082:ios:3599964893735bc6c7dafb',
    messagingSenderId: '216493554082',
    projectId: 'nuduwawithflutter',
    storageBucket: 'nuduwawithflutter.appspot.com',
    androidClientId: '216493554082-mu34upsqjma2uhdpb95b8tqtr4uvb7nk.apps.googleusercontent.com',
    iosClientId: '216493554082-o4ofn87qs7vl73mvr45go6nj55nuq192.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuduwaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFvabkzwToJabeG3AwRHMcoBDMT_q9CQ8',
    appId: '1:216493554082:ios:6d3950ca24c9fc60c7dafb',
    messagingSenderId: '216493554082',
    projectId: 'nuduwawithflutter',
    storageBucket: 'nuduwawithflutter.appspot.com',
    androidClientId: '216493554082-mu34upsqjma2uhdpb95b8tqtr4uvb7nk.apps.googleusercontent.com',
    iosClientId: '216493554082-h60qj0edcapklq5e1gr8gcmg82a2pr27.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuduwaFlutter.RunnerTests',
  );
}
